---
# Copyleft (c) 2022 Contributors to Smart Data Models initiative
#


components:
  schemas:
    OSMBuilding:
      $ref: "https://smart-data-models.github.io/dataModel.OpenStreetMap/OSMBuilding/model.yaml#OSMBuilding"
info:
  description: |
    A building or group of connected buildings from OpenStreetMap tagged with building=*. Represents the physical structure of a building, including its geometry, dimensions, materials, and functional classification. For specific functions within a building (shop, amenity, etc.) additional entities should be used.
  title: OSMBuilding
  version: "0.0.1"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - OSMBuilding
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OpenStreetMap/OSMBuilding/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OpenStreetMap/OSMBuilding/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld