---
# Copyleft (c) 2022 Contributors to Smart Data Models initiative
# 


components:
  schemas: 
    OSMManMade: 
      $ref: "https://smart-data-models.github.io/dataModel.OpenStreetMap/OSMManMade/model.yaml#/OSMManMade"
info:
  description:  |
    An artificial structure from OpenStreetMap tagged with man_made=*. This data model is a derivative work based on the OpenStreetMap Wiki, licensed under CC BY-SA 2.0 by OpenStreetMap contributors.
  title: OSMManMade
  version: "0.0.1"
openapi: "3.0.0"

paths:
  /ngsi-ld/v1/entities:
    get:
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters:
        -
          in: query
          name: type
          required: true
          schema:
            enum:
              - OSMManMade
            type: string
      responses:
        ? "200"
        :
          content:
            application/ld+json:
              examples:
                keyvalues:
                  summary: "Key-Values Pairs"
                  value:
                    -
                      $ref: "https://smart-data-models.github.io/dataModel.OpenStreetMap/OSMManMade/examples/example.json"
                normalized:
                  summary: "Normalized NGSI-LD"
                  value:
                    -
                      $ref: "https://smart-data-models.github.io/dataModel.OpenStreetMap/OSMManMade/examples/example-normalized.jsonld"
          description: OK
      tags:
        - ngsi-ld
tags:
  -
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
