---
# Copyleft (c) 2022 Contributors to Smart Data Models initiative
#


components:
  schemas:
    OSMBuildingPart:
      $ref: "https://smart-data-models.github.io/dataModel.OpenStreetMap/OSMBuildingPart/model.yaml#OSMBuildingPart"
info:
  description: |
    A part or section of a building from OpenStreetMap tagged with building:part=*. Used to represent buildings with varying heights, roof shapes, or materials across different sections, enabling 3D building visualisation (Simple 3D Buildings standard).
  title: OSMBuildingPart
  version: "0.0.1"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - OSMBuildingPart
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OpenStreetMap/OSMBuildingPart/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OpenStreetMap/OSMBuildingPart/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld