---
# Copyleft (c) 2022 Contributors to Smart Data Models initiative
#


components:
  schemas:
    OSMShop:
      $ref: "https://smart-data-models.github.io/dataModel.OpenStreetMap/OSMShop/model.yaml#OSMShop"
info:
  description: |
    A shop or retail store from OpenStreetMap tagged with shop=*. Represents establishments selling retail products directly to end customers
  title: OSMShop
  version: "0.0.1"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - OSMShop
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OpenStreetMap/OSMShop/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.OpenStreetMap/OSMShop/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld